services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tdg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  pgdata:
