[project]
name = "tdg"
version = "0.1.0"
description = "Test Data Generator Kit"
requires-python = ">=3.10"
dependencies = []
[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
